In [34]:
import pandas as pd
import numpy as np

# Importing Data

In [35]:
indices_df = pd.read_csv("../raw_data/indices_data.csv")
surface_df = pd.read_csv("../raw_data/surface_data.csv")

## Data Exploration

In [36]:
print(indices_df.describe())
surface_df.describe()

               Year         Month           Day   SWEAT index  \
count  11883.000000  11883.000000  11883.000000  11883.000000
mean    1998.286712      6.539510     15.728099    182.923858
std       11.154318      3.433968      8.819977     92.033776
min     1981.000000      1.000000      1.000000      5.800000
25%     1989.000000      4.000000      8.000000    104.600000
50%     1997.000000      7.000000     16.000000    185.300000
75%     2005.500000     10.000000     23.000000    249.050000
max     2020.000000     12.000000     31.000000    850.700000

       Showalter index  LIFTED index       K index  Cross totals index  \
count     11883.000000  11883.000000  11883.000000        11883.000000
mean          6.931743      0.521754     23.206581           15.603484
std           4.465433      7.002176     15.823667            7.171165
min          -9.600000    -21.700000    -62.300000          -36.700000
25%           4.100000     -4.300000     11.400000           11.900000
50%           6.600000     -1.400000     28.200000           17.700000
75%           9.400000      4.600000     35.800000           20.700000
max          44.100000     27.800000     62.100000           33.300000

       Vertical totals index  Totals totals index          TLCL          PLCL  \
count           11883.000000         11883.000000  11883.000000  11883.000000
mean               24.329142            39.932626    292.705253    952.021543
std                 4.109635             9.294096      6.189168     39.226386
min                 8.900000           -17.900000    254.750000    497.250000
25%                21.700000            35.400000    288.035000    935.950000
50%                23.700000            41.800000    294.790000    961.010000
75%                26.800000            45.800000    297.760000    979.870000
max                40.700000            69.800000    310.810000   1168.110000

               CINE          CAPE  PRECIPITABLE WATER  1000-500 THICKNESS
count  11883.000000  11883.000000        11883.000000        11883.000000
mean     -63.671472    900.712421           40.506825         5750.025162
std      404.003436   1332.376203           17.504832           70.235229
min   -29338.900000      0.000000          -24.400000         5530.000000
25%      -79.700000      0.000000           25.400000         5699.000000
50%      -12.900000     87.800000           38.600000         5757.000000
75%        0.000000   1544.150000           55.400000         5806.000000
max       29.000000  16555.900000           98.900000         5961.000000

               Year         Month           Day
count  14397.000000  14397.000000  14397.000000
mean    2000.326179      6.517052     15.727026
std       11.426269      3.452945      8.800485
min     1981.000000      1.000000      1.000000
25%     1990.000000      4.000000      8.000000
50%     2000.000000      7.000000     16.000000
75%     2010.000000     10.000000     23.000000
max     2020.000000     12.000000     31.000000

In [37]:
print(indices_df.info())
surface_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11883 entries, 0 to 11882
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   11883 non-null  int64
 1   Month                  11883 non-null  int64
 2   Day                    11883 non-null  int64
 3   SWEAT index            11883 non-null  float64
 4   Showalter index        11883 non-null  float64
 5   LIFTED index           11883 non-null  float64
 6   K index                11883 non-null  float64
 7   Cross totals index     11883 non-null  float64
 8   Vertical totals index  11883 non-null  float64
 9   Totals totals index    11883 non-null  float64
 10  TLCL                   11883 non-null  float64
 11  PLCL                   11883 non-null  float64
 12  CINE                   11883 non-null  float64
 13  CAPE                   11883 non-null  float64
 14  PRECIPITABLE WATER     11883 non-null  float64
 15  1000-500 THICKNESS     11883 non-null  int64
dtypes: float64(12), int64(4)
memory usage: 1.5 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14397 entries, 0 to 14396
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        14397 non-null  int64
 1   Month       14397 non-null  int64
 2   Day         14397 non-null  int64
 3   HA          14396 non-null  object
 4   TH          14396 non-null  object
 5   Unnamed: 5  14397 non-null  object
dtypes: int64(3), object(3)
memory usage: 675.0+ KB

In [38]:
print(surface_df.head(5))
indices_df.head(5)

   Year  Month  Day HA TH Unnamed: 5
0  1981      1    1  0  0
1  1981      1    2  0  0
2  1981      1    3  0  0
3  1981      1    4  0  0
4  1981      1    5  0  0

,Year,Month,Day,SWEAT index,Showalter index,LIFTED index,K index,Cross totals index,Vertical totals index,Totals totals index,TLCL,PLCL,CINE,CAPE,PRECIPITABLE WATER,1000-500 THICKNESS
0,1981,1,1,91.2,12.4,13.4,-1.4,3.0,21.7,24.7,284.41,993.98,0.0,0.0,22.8,5636
1,1981,1,2,75.7,10.2,11.3,1.6,10.2,20.1,30.3,282.11,956.13,0.0,0.0,20.4,5592
2,1981,1,4,128.3,6.9,6.9,17.5,16.3,25.3,41.6,284.79,978.71,0.0,0.0,23.8,5581
3,1981,1,5,194.2,2.8,1.2,23.5,22.5,28.1,50.6,286.68,965.77,-138.5,83.1,28.6,5578
4,1981,1,6,151.4,5.1,1.8,25.4,18.9,24.9,43.8,289.11,975.72,-112.9,47.9,33.2,5648

In [39]:
print(surface_df.count())
indices_df.count()

Year          14397
Month         14397
Day           14397
HA            14396
TH            14396
Unnamed: 5    14397
dtype: int64

Year                     11883
Month                    11883
Day                      11883
SWEAT index              11883
Showalter index          11883
LIFTED index             11883
K index                  11883
Cross totals index       11883
Vertical totals index    11883
Totals totals index      11883
TLCL                     11883
PLCL                     11883
CINE                     11883
CAPE                     11883
PRECIPITABLE WATER       11883
1000-500 THICKNESS       11883
dtype: int64

In [40]:
print(surface_df.isna().sum())
indices_df.isna().sum()

Year          0
Month         0
Day           0
HA            1
TH            1
Unnamed: 5    0
dtype: int64

Year                     0
Month                    0
Day                      0
SWEAT index              0
Showalter index          0
LIFTED index             0
K index                  0
Cross totals index       0
Vertical totals index    0
Totals totals index      0
TLCL                     0
PLCL                     0
CINE                     0
CAPE                     0
PRECIPITABLE WATER       0
1000-500 THICKNESS       0
dtype: int64

## Thunderstorm Count

In [41]:
th_count = surface_df['TH'].value_counts()
th_count

TH
0    11623
1     2772
         1
Name: count, dtype: int64

## Combining 'Year','Month','Day' columns to create single Date Column in dd/mm/YYYY format

In [ ]:
indices_df['Date'] = pd.to_datetime(indices_df[['Year','Month','Day']]).dt.strftime('%d/%m/%Y')
surface_df['Date'] = pd.to_datetime(surface_df[['Year','Month','Day']]).dt.strftime('%d/%m/%Y')

In [ ]:
surface_df.drop(columns=['Year','Month','Day', 'Unnamed: 5'], inplace=True)
indices_df.drop(columns=['Year','Month','Day'], inplace=True)

## Performing Inner Join on Surface and Indices data on Date Column

In [ ]:
merged_df = pd.merge(indices_df, surface_df, how='inner', on='Date')
merged_df.to_csv('raw_data/merged_idf_sdf.csv', index=False)

In [54]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11682 entries, 0 to 11681
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SWEAT index            11682 non-null  float64
 1   Showalter index        11682 non-null  float64
 2   LIFTED index           11682 non-null  float64
 3   K index                11682 non-null  float64
 4   Cross totals index     11682 non-null  float64
 5   Vertical totals index  11682 non-null  float64
 6   Totals totals index    11682 non-null  float64
 7   TLCL                   11682 non-null  float64
 8   PLCL                   11682 non-null  float64
 9   CINE                   11682 non-null  float64
 10  CAPE                   11682 non-null  float64
 11  PRECIPITABLE WATER     11682 non-null  float64
 12  1000-500 THICKNESS     11682 non-null  int64
 13  Date                   11682 non-null  object
 14  HA                     11681 non-null  object
 15  TH                     11681 non-null  object
dtypes: float64(12), int64(1), object(3)
memory usage: 1.4+ MB